### ISSUE TITLE
Update to work with latest version of ctrulib

### ISSUE THREAD

**Issue by JerwuQu** [cpp3ds/gl3ds#2]
Some things like GPU_KEEP have been replaced with GPU_STENCIL_KEEP in the past few months.

**Comment by Cruel** [comment]
Thanks for bringing this up. I actually have a lot of changes locally (including the GPU_KEEP fix). But I was working on a lot of experimental things and the code is a mess. I'll hopefully get those pushed soon.

**Comment by JerwuQu** [comment]
Yeah, it seems like it's also missing glGetTexImage
![image](https://cloud.githubusercontent.com/assets/3710677/10120875/9281ba3c-64d1-11e5-8802-68ccacfc1b1b.png) (building cpp3ds)

I hope you push your changes soon, I'm really eager to get started :3

**Comment by Cruel** [comment]
Glad to hear. Yeah, was working on some other stuff on cpp3ds like getting audio streaming working, and messing around with some 3D primitives and Camera class. But guess I should probably stop adding more things for a bit and focus on getting everything stable.

I'll probably have everything up-to-date in a couple days. So they can at least be usable.

**Comment by JerwuQu** [comment]
Sounds great! Looking forward to it.

**Comment by Cruel** [comment]
Okay, gl3ds should build now.

cpp3ds should build too, but requires a bunch of dependencies I need to mention, it needs to find nihstro, makerom, and bannertool for starters. Those can all be build from their respective git repos, but I'll have to document that later when I get time.
